#!/usr/bin/env python
# coding: utf-8

# In[1]:


#Armstrong No. Between range of 1042000 to 702648265


# In[4]:


for i in range(1042000,702648266):
    order=len(str(i))
    sum=0
    temp=i
    while temp>0:
        digit=temp%10
        sum+=digit**order
        temp//=10
    if i==sum:
        print("Number is armstrong",i)
        break
  


# In[ ]:




